# Generated by Django 4.1.2 on 2023-04-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_posts_is_published_posts_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='unpublished',
            field=models.BooleanField(default=True),
        ),
    ]
