# Generated by Django 4.1.2 on 2023-04-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_posts_unpublished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='unpublished',
        ),
    ]
