# Generated by Django 4.1.2 on 2023-04-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_posts_is_published_remove_posts_unpublished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
    ]
