# Generated by Django 4.1.2 on 2023-04-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='status',
            field=models.CharField(choices=[('published', 'published'), ('unpublished', 'unpublished'), ('cancelled', 'cancelled')], default='unpublished', max_length=200),
        ),
    ]
