# Generated by Django 4.1.2 on 2023-04-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_posts_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='like',
        ),
        migrations.AddField(
            model_name='posts',
            name='like',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], default='order-placed', max_length=200),
        ),
    ]
